import {pathToFileURL} from 'node:url';
import Fastify from 'fastify';import {Contract,JsonRpcProvider,formatUnits,parseUnits} from 'ethers';
import {loadConfig} from './config.mjs';import {database} from './db.mjs';import {rank} from './accounting.mjs';
import {registerAirdrop,supabaseStore} from './airdrop.mjs';
export function buildServer({config,db,provider,marketFetcher=fetch}) {
 const app=Fastify({logger:false,bodyLimit:16384});let leaderboardCache=null;
 registerAirdrop(app,{origin:config.origin,secret:config.airdropSessionSecret,store:config.supabaseUrl&&config.supabaseKey?supabaseStore({url:config.supabaseUrl,key:config.supabaseKey}):null});
 app.addHook('onRequest',async(request,reply)=>{reply.header('Cache-Control','no-store');const origin=request.headers.origin;if(origin===config.origin)reply.header('Access-Control-Allow-Origin',origin).header('Vary','Origin');});
 const unavailable=reply=>reply.code(503).send({available:false,chainId:config.chainId});
 app.get('/data-config.json',async()=>({chainId:config.chainId,tokenAddress:config.tokenAddress,collectionAddress:config.collectionAddress,pollIntervalMs:15000,requestTimeoutMs:8000,maxDataAgeMs:60000,maxQuoteAgeMs:30000,endpoints:{market:'/api/market',collection:'/api/collection',swarm:'/api/swarm',quote:'/api/quote'}}));
 async function finalized(){if(!provider)throw new Error('RPC missing');const network=await provider.getNetwork();if(Number(network.chainId)!==config.chainId)throw new Error('Wrong RPC chain');const block=await provider.send('eth_getBlockByNumber',['finalized',false]);if(!block)throw new Error('Finality unavailable');return {number:Number(BigInt(block.number)),hash:block.hash,time:Number(BigInt(block.timestamp)),observedAt:new Date().toISOString()};}
 app.get('/api/runtime',async(_,reply)=>{try{const rows=(await db.query('SELECT name,status,observed_at FROM service_state')).rows;if(!rows.length)return unavailable(reply);return{chainId:config.chainId,services:rows};}catch{return unavailable(reply);}});
 app.get('/health',async(_,reply)=>{try{await db.query('SELECT 1');return{status:'ok',chainId:config.chainId,configured:Boolean(config.rpcUrl&&config.tokenAddress&&config.collectionAddress)};}catch{return reply.code(503).send({status:'unavailable'});}});
 app.get('/api/collection',async(_,reply)=>{try{if(!config.collectionAddress)return unavailable(reply);const block=await finalized();const nft=new Contract(config.collectionAddress,['function totalSupply() view returns(uint256)'],provider);const totalSupply=Number(await nft.totalSupply({blockTag:block.number}));if(totalSupply>1000)throw new Error('Invalid supply');return{chainId:config.chainId,updatedAt:block.observedAt,collectionAddress:config.collectionAddress,totalSupply,blockNumber:block.number,blockHash:block.hash,...(totalSupply?{latestNft:{id:totalSupply,imageUrl:`${config.apiOrigin||config.origin}/api/art/${totalSupply}.svg`}}:{})};}catch{return unavailable(reply);}});
 app.get('/api/art/:id.svg',async(request,reply)=>{try{const id=Number(request.params.id);if(!Number.isSafeInteger(id)||id<1||id>1000||!config.collectionAddress)return reply.code(404).send({available:false});const block=await finalized();const nft=new Contract(config.collectionAddress,['function tokenURI(uint256) view returns(string)'],provider);const uri=await nft.tokenURI(id,{blockTag:block.number});const json=JSON.parse(Buffer.from(uri.split(',')[1],'base64'));if(!json.image.startsWith('data:image/svg+xml;base64,'))throw new Error('Invalid image');const svg=Buffer.from(json.image.split(',')[1],'base64');return reply.header('Content-Security-Policy',"default-src 'none'; sandbox").type('image/svg+xml').send(svg);}catch{return unavailable(reply);}});
 app.get('/api/swarm',async(_,reply)=>{try{const counts=await db.query("SELECT COUNT(*) FILTER(WHERE admitted_verified)::int AS requested,COUNT(*) FILTER(WHERE admitted_verified AND status IN ('completed','validated','minted'))::int AS completed,MAX(updated_at) AS observed FROM swarm_job_history");const latest=await db.query('SELECT imd_job_id,status FROM swarm_job_history WHERE admitted_verified ORDER BY token_id DESC LIMIT 1');const row=counts.rows[0];if(!row.observed)return unavailable(reply);return{chainId:config.chainId,updatedAt:new Date(row.observed).toISOString(),requested:row.requested,completed:row.completed,...(latest.rows[0]?{latestJob:{id:latest.rows[0].imd_job_id,status:({admitted:'requested',running:'running',completed:'completed',validated:'completed',minted:'completed',failed:'failed'})[latest.rows[0].status]}}:{})};}catch{return unavailable(reply);}});
 app.get('/api/market',async(_,reply)=>{try{if(!config.marketUrl||!config.tokenAddress||!config.controllerAddress||!config.imdAddress)return unavailable(reply);const response=await marketFetcher(config.marketUrl,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error('Source unavailable');const data=await response.json();if(data.tokenAddress?.toLowerCase()!==config.tokenAddress.toLowerCase()||data.chainId!==config.chainId||!Number.isFinite(data.priceUsd)||data.priceUsd<0||!Number.isFinite(data.marketCapUsd)||data.marketCapUsd<0||!Number.isFinite(Date.parse(data.updatedAt))||Date.parse(data.updatedAt)>Date.now()+5000||Date.now()-Date.parse(data.updatedAt)>60000)throw new Error('Invalid source');const block=await finalized();const imd=new Contract(config.imdAddress,['function balanceOf(address) view returns(uint256)','function decimals() view returns(uint8)'],provider);const [balance,decimals]=await Promise.all([imd.balanceOf(config.controllerAddress,{blockTag:block.number}),imd.decimals({blockTag:block.number})]);return{...data,creationPoolImd:formatUnits(balance,decimals),updatedAt:data.updatedAt,blockNumber:block.number};}catch{return unavailable(reply);}});
 app.get('/api/leaderboard',async(_,reply)=>{try{const state=(await db.query('SELECT * FROM chain_state WHERE chain_id=$1',[config.chainId])).rows[0];if(!state||Date.now()-new Date(state.observed_at)>60000)return unavailable(reply);const height=Number(state.next_block)-1;const bucket=Math.floor(height/100);if(!leaderboardCache||leaderboardCache.bucket!==bucket){const block=(await db.query('SELECT timestamp FROM chain_blocks WHERE chain_id=$1 AND number=$2',[config.chainId,height])).rows[0];const holders=(await db.query('SELECT address,balance::text,score::text,last_timestamp FROM holders WHERE chain_id=$1',[config.chainId])).rows;const allocated=(await db.query('SELECT recipient FROM allocations WHERE chain_id=$1',[config.chainId])).rows.map(r=>r.recipient);leaderboardCache={bucket,blockNumber:height,updatedAt:new Date(state.observed_at).toISOString(),holders:rank(holders,block.timestamp,config.excluded,allocated).slice(0,100)};}return{chainId:config.chainId,...leaderboardCache};}catch{return unavailable(reply);}});
 app.get('/api/quote',async(request,reply)=>{
  const q=request.query;const asset=q.asset||'IMD';if(!['ETH','IMD'].includes(asset))return reply.code(400).send({error:'invalid_asset'});if(!['buy','sell'].includes(q.side)||!/^\d+(\.\d{1,18})?$/.test(q.amount||'')||q.amount.length>80||!/[1-9]/.test(q.amount)||![50,100,300].includes(Number(q.slippageBps))||Number(q.chainId)!==config.chainId||q.tokenAddress?.toLowerCase()!==config.tokenAddress?.toLowerCase())return reply.code(400).send({error:'invalid_quote'});
  // Never quote the IMD-only router as though it were an ETH route.
  if(asset==='ETH')return reply.code(503).send({available:false,chainId:config.chainId,asset,reason:'route_unavailable'});
  try{if(!config.quoterAddress||!config.hookAddress||!config.imdAddress||!provider)return unavailable(reply);await finalized();const imdFirst=BigInt(config.imdAddress)<BigInt(config.tokenAddress);const key={currency0:imdFirst?config.imdAddress:config.tokenAddress,currency1:imdFirst?config.tokenAddress:config.imdAddress,fee:0,tickSpacing:60,hooks:config.hookAddress};const quoter=new Contract(config.quoterAddress,['function quoteExactInputSingle((tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) poolKey,bool zeroForOne,uint128 exactAmount,bytes hookData) params) returns(uint256 amountOut,uint256 gasEstimate)'],provider);const amount=parseUnits(q.amount,18);if(amount>=2n**128n)throw new Error('Amount too large');const result=await quoter.quoteExactInputSingle.staticCall({poolKey:key,zeroForOne:q.side==='buy'?imdFirst:!imdFirst,exactAmount:amount,hookData:'0x'});const now=Date.now();return{chainId:config.chainId,tokenAddress:config.tokenAddress,updatedAt:new Date(now).toISOString(),expiresAt:new Date(now+15000).toISOString(),side:q.side,asset,inputAsset:q.side==='buy'?'IMD':'IMPEPE',outputAsset:q.side==='buy'?'IMPEPE':'IMD',amountIn:q.amount,slippageBps:Number(q.slippageBps),amountOut:formatUnits(result.amountOut,18),minAmountOut:formatUnits(result.amountOut*BigInt(10000-Number(q.slippageBps))/10000n,18)};}catch{return unavailable(reply);}
 });
 app.setErrorHandler((_,request,reply)=>reply.code(500).send({error:'service_error'}));return app;
}
if(process.argv[1] && import.meta.url===pathToFileURL(process.argv[1]).href){const config=loadConfig();const db=database(config.databaseUrl);const provider=config.rpcUrl?new JsonRpcProvider(config.rpcUrl):null;const app=buildServer({config,db,provider});await app.listen({host:process.env.HOST||'127.0.0.1',port:config.port});console.log(`IMPEPE backend http://127.0.0.1:${config.port}`);for(const signal of ['SIGINT','SIGTERM'])process.on(signal,async()=>{await app.close();await db.close();provider?.destroy();process.exit(0);});}
